apiVersion: v1
kind: Secret
metadata:
  name: {{ include "payforward-backend.fullname" . }}-secrets
  labels:
    {{- include "payforward-backend.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.secrets.jwtSecret | b64enc | quote }}
